import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig, type Plugin } from "vite";
import { viteSingleFile } from "vite-plugin-singlefile";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const outDir = resolve(here, "dist");

/**
 * The MCP server serves the timetable view as one self-contained HTML string
 * (the `ui://` resource). Emit it as a TypeScript module so Next.js bundles it
 * like any other import.
 */
function emitServerModule(): Plugin {
  return {
    name: "caltrain:emit-server-module",
    apply: "build",
    closeBundle() {
      const html = readFileSync(resolve(outDir, "index.html"), "utf8");
      const target = resolve(root, "lib/generated/widget-html.ts");
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(
        target,
        `// Generated by \`npm run widget:build\` from widget/. Do not edit.\n` +
          `export const WIDGET_HTML = ${JSON.stringify(html)};\n`,
      );
      console.log(`widget → lib/generated/widget-html.ts (${(html.length / 1024).toFixed(0)} kB)`);
    },
  };
}

export default defineConfig({
  root: here,
  plugins: [react(), tailwindcss(), viteSingleFile(), emitServerModule()],
  resolve: { alias: { "@": root } },
  build: { outDir, emptyOutDir: true, reportCompressedSize: false },
});
