name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run ruff linter
        run: |
          uv run ruff check .

      - name: Run ruff formatter
        run: |
          uv run ruff format --check .

      - name: Run mypy type checker
        run: |
          uv run mypy src

      - name: Run pytest
        run: |
          uv run pytest --cov=src/caltrain_mcp --cov-report=term-missing
