name: CI & Semantic release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.13']

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Ruff (lint + fmt check)
        run: |
          uv run ruff check .
          uv run ruff format --check .

      - name: MyPy
        run: uv run mypy src

      - name: PyTest
        run: uv run pytest --cov=src/caltrain_mcp --cov-report=term-missing

  semantic_release:
    needs: test
    if: needs.test.result == 'success' && github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - uses: astral-sh/setup-uv@v6

      - name: Install semantic-release
        run: uv tool install python-semantic-release

      - name: Run semantic-release
        run: uv tool run python-semantic-release publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
