name: Refresh GTFS

on:
  schedule:
    - cron: '0 10 * * 1' # Monday 10 UTC
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - uses: astral-sh/setup-uv@v6

      - name: Download latest GTFS
        run: uv run python scripts/fetch_gtfs.py

      - name: Commit & PR if changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "caltrain-bot"
          git config user.email "caltrain-bot@users.noreply.github.com"

          if [[ -n $(git status --porcelain data/caltrain-ca-us) ]]; then
            BRANCH="gtfs-update-$(date +%F-%H%M%S)"
            git switch -c "$BRANCH"
            git add data/caltrain-ca-us
            git commit -m "chore: refresh GTFS feed"
            git push --set-upstream origin "$BRANCH"
            gh pr create --fill --base main
          else
            echo "No changes 📭"
          fi
